//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangman.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hangman.Resources.GameStrings", typeof(GameStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of available commands:.
        /// </summary>
        internal static string AvailableCommands {
            get {
                return ResourceManager.GetString("AvailableCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your name:.
        /// </summary>
        internal static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your name for the top scoreboard.
        /// </summary>
        internal static string EnterPlayerNameForLeaderboardMessage {
            get {
                return ResourceManager.GetString("EnterPlayerNameForLeaderboardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exit - quit the game.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help - reveal first hidden letter.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to “Hangman” game. Please try to guess my secret word..
        /// </summary>
        internal static string IntroductingMessage {
            get {
                return ResourceManager.GetString("IntroductingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So far you have made the following guesses: {0}.
        /// </summary>
        internal static string LetterAlreadyRevealedMessage {
            get {
                return ResourceManager.GetString("LetterAlreadyRevealedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You lose! Number of mistakes:.
        /// </summary>
        internal static string LossMessage {
            get {
                return ResourceManager.GetString("LossMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can make a total of {0} wrong guesses before you are hanged!.
        /// </summary>
        internal static string MaxWrongGuessesWarningMessage {
            get {
                return ResourceManager.GetString("MaxWrongGuessesWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your next guess: .
        /// </summary>
        internal static string NextGuess {
            get {
                return ResourceManager.GetString("NextGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of wrong guesses made: {0}.
        /// </summary>
        internal static string NumOfWrongGuessesMade {
            get {
                return ResourceManager.GetString("NumOfWrongGuessesMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already revealed the letter &quot;{0}&quot;..
        /// </summary>
        internal static string RepeatingGuessMessage {
            get {
                return ResourceManager.GetString("RepeatingGuessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restart - start a new game.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to showcommands - show available commands.
        /// </summary>
        internal static string ShowCommands {
            get {
                return ResourceManager.GetString("ShowCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to showresult - view the top scoreboard.
        /// </summary>
        internal static string ShowResult {
            get {
                return ResourceManager.GetString("ShowResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You won! Number of mistakes:.
        /// </summary>
        internal static string WinMessage {
            get {
                return ResourceManager.GetString("WinMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You scored {0} points!.
        /// </summary>
        internal static string YouScoredPtsMsg {
            get {
                return ResourceManager.GetString("YouScoredPtsMsg", resourceCulture);
            }
        }
    }
}
